# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='time_created',
            field=models.TimeField(),
        ),
    ]
