# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170623_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='time_created',
            field=models.TimeField(blank=True),
        ),
    ]
