# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='dummy',
        ),
    ]
