# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170623_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='phone_number',
            field=models.IntegerField(default=''),
        ),
    ]
