# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170621_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='blog',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='facebook',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='main_bio',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='phone_number',
            field=models.SmallIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skill1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='skill2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
