# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_portfolio_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='public_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
