# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170627_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='phone_number',
            field=models.IntegerField(default=123456789),
        ),
    ]
