# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170621_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project1_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project1_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project2_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project2_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project3_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project3_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
