# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20170621_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project1_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project2_description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project3_description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project1_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
