# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20170627_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='dummy_field',
            field=models.CharField(default='', max_length=241),
        ),
    ]
