# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolio_dummy_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='dummy_field',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='phone_number',
        ),
    ]
